version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./src/reservation_hotel:/app/src/reservation_hotel
    ports:
      - 5000:5000
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: reservation_hotel
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: